# SPDX-License-Identifier: MPL-2.0

load("@sif//kernel/arch:select.bzl", "select_arch")
load("@sif//rules:crate.bzl", "crate")
load("@sif//utils/rules.bzl", "export_path")

crate(
    name="sif_mcu",
    root="lib.rs",
    srcs=glob(["**/*.rs"]),
    deps=[
        "sif//kernel:core",
        select_arch(),
    ],
)

export_path("vmsif.ld")
