# SPDX-License-Identifier: MPL-2.0

load("@sif//tools/rules.bzl", "tool")

tool(
    name="miri",
    binary="miri",
    flake=".",
    derivation=["packages", "rust-bin"],
)

tool(
    name="rustc",
    flake=".",
    derivation=["packages", "rustc"],
)

tool(
    name="rustc-bin",
    binary="rustc",
    flake=".",
    derivation=["packages", "rust-bin"],
)
