# SPDX-License-Identifier: MPL-2.0

load("@sif//rules:crate.bzl", "crate")
load("@sif//rules:include.bzl", "include")

crate(
    name="core",
    out_name="sif_core",
    root="core/lib.rs",
    srcs=glob(["core/**/*.rs"]),
)

crate(
    name="kernel",
    out_name="sif",
    root="kernel/lib.rs",
    srcs=glob(["kernel/**/*.rs"]),
    deps=[
        ":core",
    ],
    aliased_deps={
        "sif_arch": select(
            {
                "sif//constraints:arch[arm]": "sif//kernel/arch:arm",
            },
        ),
    },
)

include(
    name="ld-include",
    files=glob(["**/*.ld"]),
)
