# SPDX-License-Identifier: MPL-2.0

load("@sif//rules:crate.bzl", "crate")

crate(
    name="arm",
    root="arm/lib.rs",
    srcs=glob(["arm/**/*.rs"]),
    deps=[
        "sif//kernel:core",
    ],
)
