# SPDX-License-Identifier: MPL-2.0

load("//constraints:rules.bzl", "constraint")

constraint(
    name="arch",
    values=[
        "aarch64",
        "arm",
        "x86_64",
        "unknown",
    ],
    default="unknown",
)

constraint(
    name="os",
    values=[
        "linux",
        "macos",
        "sif",
    ],
)

constraint(
    name="opt-level",
    values=["0", "1", "2", "3", "s", "z"],
    nullable=False,
    default="0",
)

constraint(
    name="toolchain",
    values=[
        "llvm",
    ],
    nullable=False,
    default="llvm",
)
