[toolchain]
channel = "nightly-2026-07-12"
components = [
  "miri",
  "rust-src",
  "rustc",
]
targets = [
  "aarch64-unknown-linux-gnu",
  "thumbv8m.base-none-eabi",
  "thumbv8m.main-none-eabi",
  "thumbv8m.main-none-eabihf",
  "x86_64-unknown-linux-gnu",
]
