# SPDX-License-Identifier: MPL-2.0

load("@sif//rules:elf.bzl", "elf")
load("@sif//rules:xip-elf.bzl", "xip_elf")

elf(
    name="_vmsif.elf",
    script="sif//kernel/mcu/raspberry-pi/rp2350a:vmsif.ld",
    objects=[
        "sif//kernel:kernel",
    ],
    includes=[
        "sif//kernel:ld-include",
    ],
)

xip_elf(
    name="vmsif.elf",
    elf=":_vmsif.elf",
)
