# SPDX-License-Identifier: MPL-2.0

load("//rules:elf.bzl", "elf")
load("//rules:xip-elf.bzl", "xip_elf")

elf(
    name="_vmsif.elf",
    script="//kernel/mcu/raspberry-pi/rp2350a:vmsif.ld",
    objects=[
        "//kernel:kernel",
    ],
    includes=[
        "//kernel:ld-include",
    ],
)

xip_elf(
    name="vmsif.elf",
    elf=":_vmsif.elf",
)
